import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#2a4bd9',
        'on-surface-variant': '#595c5e',
        'on-tertiary-container': '#4c007d',
        'secondary-fixed': '#82deff',
        'on-secondary-container': '#004e62',
        'tertiary-fixed': '#d299ff',
        'on-primary-fixed-variant': '#001e82',
        'tertiary-fixed-dim': '#c986ff',
        'surface-bright': '#f5f7f9',
        'on-primary': '#f2f1ff',
        'secondary-fixed-dim': '#57d2f9',
        background: '#f5f7f9',
        surface: '#f5f7f9',
        secondary: '#00647c',
        'on-tertiary-fixed-variant': '#580091',
        'tertiary-container': '#d299ff',
        'on-primary-container': '#00176b',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef1f3',
        'primary-fixed': '#879aff',
        'on-secondary-fixed': '#003a48',
        'surface-dim': '#d0d5d8',
        'on-background': '#2c2f31',
        'primary-dim': '#173dcd',
        'error-container': '#f74b6d',
        'on-secondary': '#e2f6ff',
        'on-error': '#ffefef',
        'tertiary-dim': '#7613bb',
        primary: '#2a4bd9',
        'on-primary-fixed': '#000000',
        'secondary-dim': '#00576c',
        'inverse-primary': '#7087ff',
        'inverse-surface': '#0b0f10',
        'inverse-on-surface': '#9a9d9f',
        'surface-container': '#e5e9eb',
        'surface-variant': '#d9dde0',
        'primary-container': '#879aff',
        'on-surface': '#2c2f31',
        outline: '#747779',
        'on-secondary-fixed-variant': '#00586e',
        'outline-variant': '#abadaf',
        'secondary-container': '#82deff',
        'surface-container-high': '#dfe3e6',
        'surface-container-highest': '#d9dde0',
        'primary-fixed-dim': '#748bff',
        'on-error-container': '#510017',
        'error-dim': '#a70138',
        error: '#b41340',
        'on-tertiary': '#fceeff',
        'on-tertiary-fixed': '#280046',
        tertiary: '#8329c8',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
        sm: '0.5rem',
        md: '0.75rem',
      },
      fontFamily: {
        headline: ['var(--font-manrope)', 'sans-serif'],
        display: ['var(--font-manrope)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        label: ['var(--font-inter)', 'sans-serif'],
        mono: ['var(--font-jetbrains)', 'JetBrains Mono', 'monospace'],
      },
      boxShadow: {
        ambient: '0 40px 60px -10px rgba(44, 47, 49, 0.06)',
        glow: '0 10px 20px -5px rgba(42, 75, 217, 0.20)',
        'glow-lg': '0 20px 40px -10px rgba(42, 75, 217, 0.25)',
        card: '0 20px 40px -10px rgba(44, 47, 49, 0.06)',
      },
      animation: {
        shimmer: 'shimmer 2s infinite',
        'fade-up': 'fadeUp 0.5s ease-out',
        'fade-in': 'fadeIn 0.3s ease-out',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        float: 'float 6s ease-in-out infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
    },
  },
  plugins: [],
}

export default config
