// Survey type metadata — single source of truth for all 46 types.
// Powers: SurveyTypeGallery cards, dynamic placeholders, AI prompt context,
// review badges, analytics routing, and benchmark mapping.

export const SURVEY_CATEGORIES = [
  { id: 'all',         label: 'All Types',              shortLabel: 'All',        icon: 'grid_view',          color: '#2c2f31', bg: '#e5e9eb' },
  { id: 'cx',          label: 'Customer Experience',    shortLabel: 'CX',         icon: 'sentiment_satisfied', color: '#2a4bd9', bg: '#e0e7ff' },
  { id: 'ex',          label: 'Employee Experience',    shortLabel: 'EX',         icon: 'groups',              color: '#059669', bg: '#d1fae5' },
  { id: 'education',   label: 'Education',              shortLabel: 'Education',  icon: 'school',              color: '#00647c', bg: '#f0fdfa' },
  { id: 'research',    label: 'Research',               shortLabel: 'Research',   icon: 'science',             color: '#8329c8', bg: '#f3e8ff' },
  { id: 'product',     label: 'Product',                shortLabel: 'Product',    icon: 'rocket_launch',       color: '#d97706', bg: '#fef3c7' },
  { id: 'healthcare',  label: 'Healthcare',             shortLabel: 'Healthcare', icon: 'health_and_safety',   color: '#b41340', bg: '#ffe0e6' },
  { id: 'operational', label: 'Operational',            shortLabel: 'Ops',        icon: 'settings',            color: '#595c5e', bg: '#e5e9eb' },
];

export const SURVEY_TYPES = [

  // ── Customer Experience ──────────────────────────────────────────────────
  {
    id: 'nps',
    category: 'cx',
    label: 'Net Promoter Score',
    shortLabel: 'NPS',
    description: 'Measure how likely customers are to recommend you. The gold standard for loyalty and growth tracking.',
    icon: 'thumb_up',
    color: '#2a4bd9',
    bg: '#e0e7ff',
    metrics: ['NPS Score', 'Promoter %', 'Detractor %'],
    recommended: true,
    estimatedMinutes: 2,
    questionCount: '2–4',
    tags: ['nps', 'loyalty', 'recommend', 'promoter', 'detractor', 'cx'],
    intentPlaceholder: 'e.g., Measure customer loyalty after our v3 product launch for enterprise SaaS customers…',
    suggestions: [
      'Measure customer loyalty after our recent product launch',
      'Track quarterly NPS for enterprise accounts',
      'Understand why our NPS score dropped 10 points last month',
    ],
  },
  {
    id: 'nps_relational',
    category: 'cx',
    label: 'Relational NPS',
    shortLabel: 'rNPS',
    description: 'Periodic relationship health survey sent quarterly or annually to capture overall loyalty trends.',
    icon: 'trending_up',
    color: '#2a4bd9',
    bg: '#e0e7ff',
    metrics: ['NPS Trend', 'Cohort Score', 'YoY Delta'],
    recommended: false,
    estimatedMinutes: 3,
    questionCount: '3–5',
    tags: ['rnps', 'relationship', 'periodic', 'annual', 'quarterly', 'cx'],
    intentPlaceholder: 'e.g., Annual relationship NPS for our top 500 enterprise accounts…',
    suggestions: [
      'Annual relationship health check for all customers',
      'Quarterly NPS pulse for high-value accounts',
      'Post-renewal satisfaction and loyalty measurement',
    ],
  },
  {
    id: 'csat',
    category: 'cx',
    label: 'Customer Satisfaction',
    shortLabel: 'CSAT',
    description: 'Rate a specific interaction on a 1–5 scale. Ideal for support, onboarding, and post-transaction moments.',
    icon: 'sentiment_satisfied',
    color: '#059669',
    bg: '#d1fae5',
    metrics: ['CSAT Score', 'Satisfaction %', 'Trend'],
    recommended: true,
    estimatedMinutes: 2,
    questionCount: '2–4',
    tags: ['csat', 'satisfaction', 'support', 'interaction', 'helpdesk', 'cx'],
    intentPlaceholder: 'e.g., Measure post-support satisfaction after every ticket resolution for our B2B platform…',
    suggestions: [
      'Measure satisfaction after every support ticket resolution',
      'Rate onboarding experience at the 30-day mark',
      'Post-checkout satisfaction for e-commerce customers',
    ],
  },
  {
    id: 'ces',
    category: 'cx',
    label: 'Customer Effort Score',
    shortLabel: 'CES',
    description: 'Measure how easy it was for customers to resolve their issue. Low effort = higher loyalty.',
    icon: 'bolt',
    color: '#d97706',
    bg: '#fef3c7',
    metrics: ['CES Score', 'Effort Level', 'Resolution Rate'],
    recommended: false,
    estimatedMinutes: 2,
    questionCount: '2–3',
    tags: ['ces', 'effort', 'friction', 'ease', 'resolution', 'cx'],
    intentPlaceholder: 'e.g., Measure how easy it was to resolve a billing issue via our self-serve portal…',
    suggestions: [
      'Measure effort to resolve issues via self-service portal',
      'Gauge difficulty of the returns and refunds process',
      'Assess friction in completing an account upgrade flow',
    ],
  },
  {
    id: 'voc',
    category: 'cx',
    label: 'Voice of Customer',
    shortLabel: 'VoC',
    description: 'Open-ended listening study to capture authentic customer language, needs, and unmet pain points.',
    icon: 'record_voice_over',
    color: '#8329c8',
    bg: '#f3e8ff',
    metrics: ['Themes', 'Sentiment', 'Key Phrases'],
    recommended: false,
    estimatedMinutes: 5,
    questionCount: '5–8',
    tags: ['voc', 'voice', 'qualitative', 'open-ended', 'listening', 'cx'],
    intentPlaceholder: 'e.g., Understand the language customers use to describe their biggest frustrations with our product…',
    suggestions: [
      'Capture the authentic language customers use about our product',
      'Identify unmet needs from our power user segment',
      'Understand top friction points across the customer journey',
    ],
  },

  // ── Employee Experience ──────────────────────────────────────────────────
  {
    id: 'enps',
    category: 'ex',
    label: 'Employee NPS',
    shortLabel: 'eNPS',
    description: 'Would your employees recommend working here? The fastest pulse on employer brand health.',
    icon: 'emoji_people',
    color: '#059669',
    bg: '#d1fae5',
    metrics: ['eNPS Score', 'Promoter %', 'Detractor %'],
    recommended: true,
    estimatedMinutes: 2,
    questionCount: '2–3',
    tags: ['enps', 'employee nps', 'employer brand', 'recommend', 'retention', 'ex'],
    intentPlaceholder: 'e.g., Quarterly eNPS pulse for a 300-person tech company post-acquisition…',
    suggestions: [
      'Quarterly eNPS pulse for the entire organization',
      'Department-level eNPS after a major restructuring',
      'eNPS tracking following return-to-office policy change',
    ],
  },
  {
    id: 'pulse',
    category: 'ex',
    label: 'Pulse Check',
    shortLabel: 'Pulse',
    description: 'Short weekly or bi-weekly check-in on team morale, key blockers, and workload balance.',
    icon: 'favorite',
    color: '#b41340',
    bg: '#ffe0e6',
    metrics: ['Morale Score', 'Blockers', 'Workload Index'],
    recommended: true,
    estimatedMinutes: 2,
    questionCount: '3–5',
    tags: ['pulse', 'weekly', 'morale', 'team health', 'blockers', 'ex'],
    intentPlaceholder: 'e.g., Weekly pulse for our 50-person engineering team to surface morale and blockers…',
    suggestions: [
      'Weekly morale check-in for remote engineering teams',
      'Bi-weekly workload and stress pulse survey',
      'Monday motivation and blocker survey for product teams',
    ],
  },
  {
    id: 'engagement',
    category: 'ex',
    label: 'Engagement Survey',
    shortLabel: 'Engagement',
    description: 'Annual deep-dive using validated engagement drivers. Benchmarkable against Gallup Q12 standards.',
    icon: 'groups',
    color: '#059669',
    bg: '#d1fae5',
    metrics: ['Engagement Score', 'Driver Analysis', 'Benchmark'],
    recommended: false,
    estimatedMinutes: 10,
    questionCount: '20–40',
    tags: ['engagement', 'annual', 'gallup', 'drivers', 'benchmark', 'ex'],
    intentPlaceholder: 'e.g., Annual engagement survey for 200-person company, benchmarked against SaaS industry…',
    suggestions: [
      'Annual engagement survey benchmarked against industry peers',
      'Mid-year engagement pulse following strategic changes',
      'Post-merger culture and engagement assessment',
    ],
  },
  {
    id: 'exit_interview',
    category: 'ex',
    label: 'Exit Interview',
    shortLabel: 'Exit',
    description: 'Capture honest offboarding feedback to understand why employees leave and reduce turnover.',
    icon: 'exit_to_app',
    color: '#d97706',
    bg: '#fef3c7',
    metrics: ['Turnover Reasons', 'Manager Score', 'Culture Flags'],
    recommended: false,
    estimatedMinutes: 8,
    questionCount: '10–15',
    tags: ['exit', 'offboarding', 'turnover', 'attrition', 'ex'],
    intentPlaceholder: 'e.g., Exit interview for voluntarily departing employees across all departments…',
    suggestions: [
      'Exit interview for voluntary departures at all levels',
      'Engineering team attrition root cause analysis',
      'Post-layoff feedback for organizational learning',
    ],
  },
  {
    id: '360_feedback',
    category: 'ex',
    label: '360° Feedback',
    shortLabel: '360°',
    description: 'Multi-rater feedback from peers, direct reports, and managers for leadership development.',
    icon: 'sync_alt',
    color: '#00647c',
    bg: '#f0fdfa',
    metrics: ['Competency Scores', 'Blind Spots', 'Strengths'],
    recommended: false,
    estimatedMinutes: 12,
    questionCount: '20–35',
    tags: ['360', 'multi-rater', 'leadership', 'development', 'peers', 'ex'],
    intentPlaceholder: 'e.g., 360° feedback for senior leaders during our annual performance cycle…',
    suggestions: [
      '360° feedback for all people managers during mid-year cycle',
      'Leadership development 360 for high-potential employees',
      'Team health 360 following an organizational change',
    ],
  },
  {
    id: 'onboarding_feedback',
    category: 'ex',
    label: 'Onboarding Feedback',
    shortLabel: 'Onboarding',
    description: 'Capture new hire experience at 30, 60, and 90 days to improve first impressions and ramp time.',
    icon: 'waving_hand',
    color: '#059669',
    bg: '#d1fae5',
    metrics: ['Onboarding Score', 'Clarity Index', 'Integration Rate'],
    recommended: false,
    estimatedMinutes: 5,
    questionCount: '8–12',
    tags: ['onboarding', 'new hire', '30 day', '90 day', 'ramp', 'ex'],
    intentPlaceholder: 'e.g., 30-day onboarding check-in for new engineering and product hires…',
    suggestions: [
      '30-day new hire onboarding experience check-in',
      '90-day onboarding effectiveness assessment',
      'Remote onboarding quality survey for Q1 new hires',
    ],
  },
  {
    id: 'manager_effectiveness',
    category: 'ex',
    label: 'Manager Effectiveness',
    shortLabel: 'Manager',
    description: 'Upward feedback to help managers grow — anonymous ratings on communication, support, and clarity.',
    icon: 'manage_accounts',
    color: '#2a4bd9',
    bg: '#e0e7ff',
    metrics: ['Manager Score', 'Communication', 'Trust Index'],
    recommended: false,
    estimatedMinutes: 6,
    questionCount: '10–15',
    tags: ['manager', 'upward feedback', 'leadership', 'communication', 'ex'],
    intentPlaceholder: 'e.g., Anonymous upward feedback on manager communication and team support…',
    suggestions: [
      'Anonymous upward feedback for all people managers',
      'Manager effectiveness pulse after a major project delivery',
      'Leadership communication score for director-level managers',
    ],
  },
  {
    id: 'dei_climate',
    category: 'ex',
    label: 'DEI Climate',
    shortLabel: 'DEI',
    description: 'Measure belonging, inclusion, and psychological safety across demographic and role segments.',
    icon: 'diversity_3',
    color: '#8329c8',
    bg: '#f3e8ff',
    metrics: ['Belonging Score', 'Inclusion Index', 'Safety Score'],
    recommended: false,
    estimatedMinutes: 8,
    questionCount: '15–25',
    tags: ['dei', 'diversity', 'inclusion', 'belonging', 'psychological safety', 'ex'],
    intentPlaceholder: 'e.g., DEI climate assessment measuring belonging and inclusion across departments…',
    suggestions: [
      'Annual DEI climate survey across all employee segments',
      'Post-DEI initiative effectiveness measurement',
      'Belonging and psychological safety assessment for remote teams',
    ],
  },
  {
    id: 'wellbeing',
    category: 'ex',
    label: 'Wellbeing Check-in',
    shortLabel: 'Wellbeing',
    description: 'Monitor employee mental health, stress, and burnout risk before they become attrition signals.',
    icon: 'spa',
    color: '#059669',
    bg: '#d1fae5',
    metrics: ['Wellbeing Score', 'Burnout Risk', 'Work-Life Balance'],
    recommended: false,
    estimatedMinutes: 4,
    questionCount: '6–10',
    tags: ['wellbeing', 'mental health', 'burnout', 'stress', 'work-life', 'ex'],
    intentPlaceholder: 'e.g., Monthly wellbeing check-in to monitor stress and burnout risk across teams…',
    suggestions: [
      'Monthly wellbeing and stress check-in for remote teams',
      'Burnout risk early warning survey for engineering teams',
      'Work-life balance assessment following new OKR cycle',
    ],
  },

  // ── Education / University ───────────────────────────────────────────────
  {
    id: 'course_evaluation',
    category: 'education',
    label: 'Course Evaluation',
    shortLabel: 'Course Eval',
    description: 'End-of-term student ratings of course content, instructor effectiveness, and learning experience.',
    icon: 'school',
    color: '#00647c',
    bg: '#f0fdfa',
    metrics: ['Course Rating', 'Instructor Score', 'Learning Outcome'],
    recommended: true,
    estimatedMinutes: 5,
    questionCount: '10–15',
    tags: ['course', 'instructor', 'teaching', 'semester', 'classroom', 'education'],
    intentPlaceholder: 'e.g., End-of-semester evaluation for CS 301 — 120 undergraduate students…',
    suggestions: [
      'End-of-semester course and instructor evaluation',
      'Mid-semester course feedback to improve delivery',
      'Online course quality assessment for asynchronous learners',
    ],
  },
  {
    id: 'student_satisfaction',
    category: 'education',
    label: 'Student Satisfaction',
    shortLabel: 'Student Sat',
    description: 'Periodic survey covering campus services, housing, dining, academic support, and overall wellbeing.',
    icon: 'auto_stories',
    color: '#00647c',
    bg: '#f0fdfa',
    metrics: ['Satisfaction Score', 'Service Ratings', 'Retention Risk'],
    recommended: false,
    estimatedMinutes: 7,
    questionCount: '15–20',
    tags: ['student', 'campus', 'satisfaction', 'services', 'housing', 'education'],
    intentPlaceholder: 'e.g., Annual student satisfaction survey for 5,000 undergraduates at a liberal arts college…',
    suggestions: [
      'Annual student satisfaction across campus services',
      'First-year student experience check-in at Week 6',
      'Graduate student program satisfaction assessment',
    ],
  },
  {
    id: 'institutional_research',
    category: 'education',
    label: 'Institutional Research',
    shortLabel: 'IR Survey',
    description: 'Formal IRB-approved or accreditation research surveys for data-driven institutional decisions.',
    icon: 'account_balance',
    color: '#2a4bd9',
    bg: '#e0e7ff',
    metrics: ['Response Rate', 'Data Quality', 'IRB Compliance'],
    recommended: false,
    estimatedMinutes: 15,
    questionCount: '25–50',
    tags: ['IRB', 'accreditation', 'institutional', 'research', 'compliance', 'education'],
    intentPlaceholder: 'e.g., IRB-approved study on first-generation student retention factors…',
    suggestions: [
      'IRB-approved study on student retention factors',
      'Accreditation self-study data collection survey',
      'Strategic plan assessment survey for board reporting',
    ],
  },
  {
    id: 'peer_assessment',
    category: 'education',
    label: 'Peer Assessment',
    shortLabel: 'Peer Review',
    description: 'Student-to-student peer evaluation for group projects, participation, and team contribution.',
    icon: 'supervised_user_circle',
    color: '#8329c8',
    bg: '#f3e8ff',
    metrics: ['Peer Scores', 'Contribution Rating', 'Collaboration Index'],
    recommended: false,
    estimatedMinutes: 6,
    questionCount: '8–12',
    tags: ['peer', 'group work', 'team', 'collaboration', 'contribution', 'education'],
    intentPlaceholder: 'e.g., Peer assessment for capstone group projects in MBA program…',
    suggestions: [
      'Group project peer contribution assessment',
      'Seminar participation and peer engagement review',
      'Team collaboration quality peer review for co-ops',
    ],
  },
  {
    id: 'learning_outcomes',
    category: 'education',
    label: 'Learning Outcomes',
    shortLabel: 'Learning',
    description: 'Pre/post knowledge and competency assessment to measure educational efficacy and skill growth.',
    icon: 'psychology',
    color: '#d97706',
    bg: '#fef3c7',
    metrics: ['Knowledge Gain', 'Competency Score', 'Pre/Post Delta'],
    recommended: false,
    estimatedMinutes: 10,
    questionCount: '15–30',
    tags: ['learning', 'outcomes', 'knowledge', 'competency', 'pre-post', 'education'],
    intentPlaceholder: 'e.g., Pre/post knowledge assessment for a data literacy bootcamp — 200 participants…',
    suggestions: [
      'Pre/post knowledge assessment for a training bootcamp',
      'Competency measurement for an MBA elective course',
      'Skills gap analysis before a professional development program',
    ],
  },
  {
    id: 'alumni_engagement',
    category: 'education',
    label: 'Alumni Engagement',
    shortLabel: 'Alumni',
    description: 'Post-graduation feedback on career outcomes, program value, and giving or re-engagement interest.',
    icon: 'diversity_1',
    color: '#00647c',
    bg: '#f0fdfa',
    metrics: ['Career Outcome', 'Program Value', 'Engagement Score'],
    recommended: false,
    estimatedMinutes: 8,
    questionCount: '12–18',
    tags: ['alumni', 'graduation', 'career', 'giving', 'engagement', 'education'],
    intentPlaceholder: 'e.g., 5-year alumni survey on career outcomes and program ROI for Class of 2019…',
    suggestions: [
      '5-year alumni career outcome and program value survey',
      'Annual alumni giving and engagement interest survey',
      'Recent graduate (1-year out) career satisfaction assessment',
    ],
  },
  {
    id: 'faculty_feedback',
    category: 'education',
    label: 'Faculty Feedback',
    shortLabel: 'Faculty',
    description: 'Student feedback on faculty accessibility, responsiveness, and professional development support.',
    icon: 'person_raised_hand',
    color: '#2a4bd9',
    bg: '#e0e7ff',
    metrics: ['Accessibility Score', 'Responsiveness', 'Support Rating'],
    recommended: false,
    estimatedMinutes: 5,
    questionCount: '8–12',
    tags: ['faculty', 'professor', 'accessibility', 'support', 'office hours', 'education'],
    intentPlaceholder: 'e.g., Faculty responsiveness and office hours satisfaction survey for graduate students…',
    suggestions: [
      'Faculty office hours and accessibility feedback',
      'Thesis advisor effectiveness survey for PhD candidates',
      'Department chair leadership feedback from faculty',
    ],
  },
  {
    id: 'program_evaluation',
    category: 'education',
    label: 'Program Evaluation',
    shortLabel: 'Program Eval',
    description: 'Comprehensive degree program or curriculum review for accreditation and continuous improvement.',
    icon: 'workspace_premium',
    color: '#8329c8',
    bg: '#f3e8ff',
    metrics: ['Program Score', 'Curriculum Rating', 'Career Prep'],
    recommended: false,
    estimatedMinutes: 12,
    questionCount: '20–30',
    tags: ['program', 'curriculum', 'degree', 'accreditation', 'review', 'education'],
    intentPlaceholder: 'e.g., Comprehensive evaluation of our 2-year MBA program for AACSB accreditation…',
    suggestions: [
      'Degree program review for accreditation preparation',
      'Curriculum effectiveness survey for program redesign',
      'Interdisciplinary program quality assessment',
    ],
  },

  // ── Research ────────────────────────────────────────────────────────────
  {
    id: 'market_research',
    category: 'research',
    label: 'Market Research',
    shortLabel: 'Market',
    description: 'Understand market size, customer segments, buying behavior, and competitive positioning.',
    icon: 'bar_chart',
    color: '#8329c8',
    bg: '#f3e8ff',
    metrics: ['Segment Size', 'Purchase Intent', 'Awareness %'],
    recommended: true,
    estimatedMinutes: 10,
    questionCount: '15–25',
    tags: ['market', 'segment', 'buying', 'competitive', 'TAM', 'research'],
    intentPlaceholder: 'e.g., Understand willingness to pay and buying triggers for our new B2B pricing tier…',
    suggestions: [
      'TAM/SAM estimation for new market entry',
      'Buyer persona validation for B2B mid-market segment',
      'Competitive switching intent and brand awareness study',
    ],
  },
  {
    id: 'academic',
    category: 'research',
    label: 'Academic Research',
    shortLabel: 'Academic',
    description: 'General-purpose IRB-compliant research instrument with validated scales and ethical consent flows.',
    icon: 'science',
    color: '#8329c8',
    bg: '#f3e8ff',
    metrics: ["Reliability (α)", 'Validity', 'Sample Power'],
    recommended: false,
    estimatedMinutes: 15,
    questionCount: '20–50',
    tags: ['IRB', 'academic', 'validated scales', 'Likert', 'research'],
    intentPlaceholder: 'e.g., Cross-sectional study on technology adoption attitudes among healthcare SMBs…',
    suggestions: [
      'IRB-approved cross-sectional survey study',
      'Validated scale administration for psychology research',
      'Mixed-methods survey for dissertation data collection',
    ],
  },
  {
    id: 'conjoint',
    category: 'research',
    label: 'Conjoint Analysis',
    shortLabel: 'Conjoint',
    description: 'Trade-off study to reveal which product attributes matter most — essential for pricing and packaging.',
    icon: 'tune',
    color: '#00647c',
    bg: '#f0fdfa',
    metrics: ['Attribute Utility', 'Willingness to Pay', 'Market Share'],
    recommended: false,
    estimatedMinutes: 12,
    questionCount: '8–16 tasks',
    tags: ['conjoint', 'trade-off', 'pricing', 'attributes', 'discrete choice', 'research'],
    intentPlaceholder: 'e.g., Conjoint to understand price/feature trade-offs for our enterprise tier packaging…',
    suggestions: [
      'Product feature trade-off study for pricing strategy',
      'Packaging and bundle optimization conjoint',
      'Service attribute importance for hospitality product',
    ],
  },
  {
    id: 'maxdiff',
    category: 'research',
    label: 'MaxDiff Study',
    shortLabel: 'MaxDiff',
    description: 'Best-worst scaling to reliably prioritize features, messages, or benefits from a large set.',
    icon: 'compare_arrows',
    color: '#8329c8',
    bg: '#f3e8ff',
    metrics: ['Utility Scores', 'Priority Rank', 'Discriminability'],
    recommended: false,
    estimatedMinutes: 8,
    questionCount: '10–20 tasks',
    tags: ['maxdiff', 'best-worst', 'priority', 'rank', 'features', 'research'],
    intentPlaceholder: 'e.g., MaxDiff to prioritize our 20 roadmap features with enterprise customers…',
    suggestions: [
      'Feature prioritization MaxDiff for product roadmap decisions',
      'Marketing message testing — best/worst resonance study',
      'Benefit importance ranking for brand positioning research',
    ],
  },
  {
    id: 'opinion_poll',
    category: 'research',
    label: 'Opinion Poll',
    shortLabel: 'Poll',
    description: 'Public opinion or community pulse. Fast, lightweight, and shareable. Ideal for social research.',
    icon: 'how_to_vote',
    color: '#2a4bd9',
    bg: '#e0e7ff',
    metrics: ['Opinion Distribution', 'Segment Breakdown', 'Trend'],
    recommended: false,
    estimatedMinutes: 3,
    questionCount: '3–8',
    tags: ['opinion', 'poll', 'public', 'community', 'voting', 'research'],
    intentPlaceholder: 'e.g., Public poll on AI regulation attitudes among knowledge workers…',
    suggestions: [
      'Industry sentiment poll for a thought leadership report',
      'Community feature vote for open-source project',
      'Public opinion on emerging technology adoption',
    ],
  },
  {
    id: 'longitudinal',
    category: 'research',
    label: 'Longitudinal Study',
    shortLabel: 'Longitudinal',
    description: 'Multi-wave panel study tracking the same cohort across time for change and causality analysis.',
    icon: 'timeline',
    color: '#00647c',
    bg: '#f0fdfa',
    metrics: ['Change Score', 'Attrition Rate', 'Wave Completion'],
    recommended: false,
    estimatedMinutes: 10,
    questionCount: '15–30 per wave',
    tags: ['panel', 'longitudinal', 'cohort', 'multi-wave', 'tracking', 'research'],
    intentPlaceholder: 'e.g., 6-month panel study tracking remote work impact on productivity and wellbeing…',
    suggestions: [
      '6-month panel study on remote work impact',
      'Annual cohort tracking for customer health monitoring',
      'Pre/post intervention study with 3-month follow-up',
    ],
  },
  {
    id: 'diary_study',
    category: 'research',
    label: 'Diary Study',
    shortLabel: 'Diary',
    description: 'Daily or weekly self-report capturing in-the-moment experiences over time. Rich, naturalistic data.',
    icon: 'edit_note',
    color: '#d97706',
    bg: '#fef3c7',
    metrics: ['Daily Reports', 'Experience Themes', 'Mood Trend'],
    recommended: false,
    estimatedMinutes: 3,
    questionCount: '3–8 per entry',
    tags: ['diary', 'daily', 'experience sampling', 'ESM', 'in-the-moment', 'research'],
    intentPlaceholder: 'e.g., 2-week diary study on daily pain points in our enterprise product workflow…',
    suggestions: [
      '2-week daily diary on product usage pain points',
      'Weekly experience sampling for remote worker wellbeing',
      'Daily mood and workflow friction diary for UX research',
    ],
  },

  // ── Product ──────────────────────────────────────────────────────────────
  {
    id: 'pmf',
    category: 'product',
    label: 'Product-Market Fit',
    shortLabel: 'PMF',
    description: "Sean Ellis test — measure what % of users would be 'very disappointed' without your product.",
    icon: 'rocket_launch',
    color: '#d97706',
    bg: '#fef3c7',
    metrics: ['PMF Score', 'Must-Have %', 'Segment Fit'],
    recommended: true,
    estimatedMinutes: 4,
    questionCount: '4–6',
    tags: ['PMF', 'product-market fit', 'Sean Ellis', 'must-have', 'startup', 'product'],
    intentPlaceholder: 'e.g., PMF survey for our B2B SaaS product targeting 500 active power users…',
    suggestions: [
      'PMF measurement for active users of our core product',
      'Must-have score for a new feature before scaling',
      'Sean Ellis test after entering a new vertical market',
    ],
  },
  {
    id: 'feature_request',
    category: 'product',
    label: 'Feature Prioritization',
    shortLabel: 'Features',
    description: 'Rank and prioritize features from your backlog against what customers actually want most.',
    icon: 'star',
    color: '#d97706',
    bg: '#fef3c7',
    metrics: ['Priority Score', 'Want %', 'Willingness to Pay'],
    recommended: false,
    estimatedMinutes: 6,
    questionCount: '8–12',
    tags: ['features', 'roadmap', 'prioritization', 'backlog', 'RICE', 'product'],
    intentPlaceholder: 'e.g., Prioritize Q3 roadmap features with our power users and enterprise accounts…',
    suggestions: [
      'Q3 roadmap prioritization with power users',
      'Feature ranking for enterprise tier expansion',
      'API vs. UI improvements priority study',
    ],
  },
  {
    id: 'usability',
    category: 'product',
    label: 'Usability Study',
    shortLabel: 'Usability',
    description: 'Measure ease of use, task completion, and friction points in your product or prototype.',
    icon: 'touch_app',
    color: '#2a4bd9',
    bg: '#e0e7ff',
    metrics: ['SUS Score', 'Task Completion', 'Error Rate'],
    recommended: false,
    estimatedMinutes: 8,
    questionCount: '10–15',
    tags: ['usability', 'UX', 'SUS', 'task completion', 'prototype', 'product'],
    intentPlaceholder: 'e.g., Usability test for our new onboarding flow redesign with first-time users…',
    suggestions: [
      'Post-task usability rating for new onboarding flow',
      'SUS score measurement for mobile app redesign',
      'Navigation and information architecture usability test',
    ],
  },
  {
    id: 'concept_test',
    category: 'product',
    label: 'Concept Test',
    shortLabel: 'Concept',
    description: 'Validate a new product idea, feature concept, or messaging before investing in development.',
    icon: 'lightbulb',
    color: '#d97706',
    bg: '#fef3c7',
    metrics: ['Appeal Score', 'Uniqueness', 'Purchase Intent'],
    recommended: false,
    estimatedMinutes: 7,
    questionCount: '10–15',
    tags: ['concept', 'ideation', 'validation', 'prototype', 'new product', 'product'],
    intentPlaceholder: 'e.g., Concept test for our AI-powered email triage tool with knowledge workers…',
    suggestions: [
      'New product concept validation with target segment',
      'Feature concept appeal and uniqueness test',
      'Landing page copy A/B concept test',
    ],
  },
  {
    id: 'brand_tracking',
    category: 'product',
    label: 'Brand Tracking',
    shortLabel: 'Brand',
    description: 'Monitor brand awareness, perception, and competitive positioning over time.',
    icon: 'branding_watermark',
    color: '#8329c8',
    bg: '#f3e8ff',
    metrics: ['Aided Awareness', 'Brand Score', 'Consideration'],
    recommended: false,
    estimatedMinutes: 8,
    questionCount: '12–20',
    tags: ['brand', 'awareness', 'perception', 'competitive', 'tracking', 'product'],
    intentPlaceholder: 'e.g., Quarterly brand tracking study among our ICP in the data infrastructure space…',
    suggestions: [
      'Quarterly brand awareness and perception study',
      'Post-rebrand perception shift measurement',
      'Competitive brand consideration and preference tracking',
    ],
  },
  {
    id: 'competitive',
    category: 'product',
    label: 'Competitive Analysis',
    shortLabel: 'Competitive',
    description: 'Benchmark against competitors on key attributes and understand why customers switch.',
    icon: 'insights',
    color: '#2a4bd9',
    bg: '#e0e7ff',
    metrics: ['Win/Loss Rate', 'Attribute Comparison', 'Switch Intent'],
    recommended: false,
    estimatedMinutes: 8,
    questionCount: '12–18',
    tags: ['competitive', 'benchmarking', 'win/loss', 'switching', 'comparison', 'product'],
    intentPlaceholder: 'e.g., Understand why customers choose us vs. Competitor X in the mid-market segment…',
    suggestions: [
      'Win/loss analysis for enterprise deals last quarter',
      'Competitive switching intent study among churned users',
      'Head-to-head attribute comparison with top 3 competitors',
    ],
  },

  // ── Healthcare ───────────────────────────────────────────────────────────
  {
    id: 'patient_satisfaction',
    category: 'healthcare',
    label: 'Patient Satisfaction',
    shortLabel: 'Patient Sat',
    description: 'HCAHPS-aligned patient experience surveys for hospitals, clinics, and telehealth providers.',
    icon: 'health_and_safety',
    color: '#b41340',
    bg: '#ffe0e6',
    metrics: ['HCAHPS Score', 'Return Intent', 'Care Rating'],
    recommended: false,
    estimatedMinutes: 5,
    questionCount: '10–15',
    tags: ['HCAHPS', 'patient', 'hospital', 'healthcare', 'care quality'],
    intentPlaceholder: 'e.g., Post-visit patient satisfaction survey for outpatient clinic following telehealth consultation…',
    suggestions: [
      'Post-visit satisfaction for outpatient clinic patients',
      'Telehealth experience quality assessment',
      'Emergency department care quality survey',
    ],
  },
  {
    id: 'clinical_outcomes',
    category: 'healthcare',
    label: 'Clinical Outcomes',
    shortLabel: 'Clinical',
    description: 'Patient-reported outcome measures (PROMs) tracking health status, symptoms, and quality of life.',
    icon: 'biotech',
    color: '#b41340',
    bg: '#ffe0e6',
    metrics: ['PROM Score', 'Symptom Change', 'QoL Index'],
    recommended: false,
    estimatedMinutes: 10,
    questionCount: '15–30',
    tags: ['PROM', 'outcomes', 'symptoms', 'quality of life', 'clinical', 'healthcare'],
    intentPlaceholder: 'e.g., PRO measurement for chronic pain patients 3 months post-intervention…',
    suggestions: [
      'Pre/post treatment quality of life measurement',
      'Chronic condition symptom tracking PRO survey',
      '6-week post-surgical outcome assessment',
    ],
  },
  {
    id: 'hcp_feedback',
    category: 'healthcare',
    label: 'Provider Feedback',
    shortLabel: 'Provider',
    description: 'Healthcare provider and staff satisfaction, burnout risk, and care delivery workflow feedback.',
    icon: 'stethoscope',
    color: '#b41340',
    bg: '#ffe0e6',
    metrics: ['Provider Satisfaction', 'Burnout Score', 'Workflow Rating'],
    recommended: false,
    estimatedMinutes: 6,
    questionCount: '10–15',
    tags: ['provider', 'physician', 'nurse', 'staff', 'burnout', 'healthcare'],
    intentPlaceholder: 'e.g., Physician and nursing staff satisfaction and burnout risk survey at regional hospital…',
    suggestions: [
      'Physician satisfaction and burnout risk assessment',
      'Nursing staff workflow and patient safety culture survey',
      'Healthcare team communication and collaboration feedback',
    ],
  },

  // ── Operational ──────────────────────────────────────────────────────────
  {
    id: 'kiosk',
    category: 'operational',
    label: 'Kiosk / In-Person',
    shortLabel: 'Kiosk',
    description: 'Tablet or touchscreen kiosk survey for retail, hospitality, events, and waiting rooms.',
    icon: 'tablet_mac',
    color: '#595c5e',
    bg: '#e5e9eb',
    metrics: ['Response Volume', 'Location Score', 'Time-of-Day Trend'],
    recommended: false,
    estimatedMinutes: 1,
    questionCount: '1–3',
    tags: ['kiosk', 'tablet', 'in-person', 'retail', 'point-of-experience', 'operational'],
    intentPlaceholder: 'e.g., 1-question kiosk survey at hotel check-out for instant satisfaction score…',
    suggestions: [
      '1-touch kiosk rating at hotel checkout counter',
      'Retail store exit satisfaction kiosk',
      'Hospital waiting room experience kiosk',
    ],
  },
  {
    id: 'intercept',
    category: 'operational',
    label: 'Website Intercept',
    shortLabel: 'Intercept',
    description: 'Pop-up or slide-in survey triggered by user behavior — exit intent, scroll depth, or time on page.',
    icon: 'ads_click',
    color: '#d97706',
    bg: '#fef3c7',
    metrics: ['Intercept Rate', 'Friction Score', 'Segment Fit'],
    recommended: false,
    estimatedMinutes: 2,
    questionCount: '2–4',
    tags: ['intercept', 'exit intent', 'popup', 'website', 'behavioral trigger', 'operational'],
    intentPlaceholder: 'e.g., Exit-intent survey on pricing page to capture why visitors are leaving without converting…',
    suggestions: [
      'Exit-intent survey to understand pricing page abandonment',
      'Time-on-page intercept for docs/help center feedback',
      'Post-checkout intercept for conversion experience feedback',
    ],
  },
  {
    id: 'in_product',
    category: 'operational',
    label: 'In-Product Feedback',
    shortLabel: 'In-Product',
    description: 'Embedded survey inside your product for logged-in users — contextual, low-friction, high-response.',
    icon: 'integration_instructions',
    color: '#2a4bd9',
    bg: '#e0e7ff',
    metrics: ['In-App Response Rate', 'Feature Score', 'Context Signal'],
    recommended: false,
    estimatedMinutes: 2,
    questionCount: '2–4',
    tags: ['in-product', 'embedded', 'in-app', 'contextual', 'SDK', 'operational'],
    intentPlaceholder: 'e.g., Post-feature-use survey shown after a user completes their first AI analysis…',
    suggestions: [
      'Post-feature survey after first use of a new capability',
      'Dashboard satisfaction survey for power users',
      'Upgrade intent survey shown to free tier users',
    ],
  },
  {
    id: 'post_transaction',
    category: 'operational',
    label: 'Post-Transaction',
    shortLabel: 'Post-TX',
    description: 'Triggered immediately after a purchase, support resolution, or any high-value transaction.',
    icon: 'receipt',
    color: '#059669',
    bg: '#d1fae5',
    metrics: ['CSAT Score', 'Repurchase Intent', 'Issue Rate'],
    recommended: false,
    estimatedMinutes: 2,
    questionCount: '2–4',
    tags: ['post-purchase', 'transaction', 'support', 'e-commerce', 'triggered', 'operational'],
    intentPlaceholder: 'e.g., Post-purchase survey triggered 24h after order delivery for e-commerce platform…',
    suggestions: [
      'Post-purchase experience survey sent 24h after delivery',
      'Post-support resolution CSAT via email/SMS',
      'Post-subscription upgrade experience check-in',
    ],
  },
  {
    id: 'event_feedback',
    category: 'operational',
    label: 'Event Feedback',
    shortLabel: 'Event',
    description: 'Capture conference, webinar, or in-person event feedback while the experience is fresh.',
    icon: 'event',
    color: '#8329c8',
    bg: '#f3e8ff',
    metrics: ['Event NPS', 'Session Ratings', 'Return Intent'],
    recommended: false,
    estimatedMinutes: 4,
    questionCount: '6–10',
    tags: ['event', 'conference', 'webinar', 'workshop', 'post-event', 'operational'],
    intentPlaceholder: 'e.g., Post-conference feedback for 800 attendees at our annual SaaS Summit…',
    suggestions: [
      'Post-conference overall experience and session ratings',
      'Webinar content quality and speaker feedback',
      'Virtual event engagement and technical quality survey',
    ],
  },
  {
    id: 'quiz',
    category: 'operational',
    label: 'Quiz',
    shortLabel: 'Quiz',
    description: 'Scored assessment with right/wrong answers — ideal for training, certification, or lead qualification.',
    icon: 'quiz',
    color: '#2a4bd9',
    bg: '#e0e7ff',
    metrics: ['Score Distribution', 'Pass Rate', 'Completion Rate'],
    recommended: false,
    estimatedMinutes: 8,
    questionCount: '10–20',
    tags: ['quiz', 'assessment', 'scoring', 'certification', 'training', 'operational'],
    intentPlaceholder: 'e.g., Product knowledge certification quiz for new sales team members…',
    suggestions: [
      'Product knowledge certification quiz for sales team',
      'Lead qualification quiz for marketing campaigns',
      'Customer training course completion assessment',
    ],
  },
  {
    id: 'registration',
    category: 'operational',
    label: 'Registration Form',
    shortLabel: 'Registration',
    description: 'Event sign-up, waitlist, interest form, or any structured data collection workflow.',
    icon: 'how_to_reg',
    color: '#00647c',
    bg: '#f0fdfa',
    metrics: ['Sign-up Rate', 'Completion Rate', 'Lead Quality'],
    recommended: false,
    estimatedMinutes: 3,
    questionCount: '4–8',
    tags: ['registration', 'sign-up', 'waitlist', 'form', 'event', 'operational'],
    intentPlaceholder: 'e.g., Conference registration with dietary and session preferences for 300 attendees…',
    suggestions: [
      'Conference registration with session preferences',
      'Product waitlist with ICP qualification questions',
      'Workshop sign-up with role and goal data capture',
    ],
  },
  {
    id: 'custom',
    category: 'operational',
    label: 'Custom Survey',
    shortLabel: 'Custom',
    description: 'Start from a blank canvas. Full AI assistance, full control over question types, logic, and flow.',
    icon: 'dashboard_customize',
    color: '#2c2f31',
    bg: '#e5e9eb',
    metrics: ['Fully Custom', 'Any Metrics', 'Any Format'],
    recommended: false,
    estimatedMinutes: null,
    questionCount: 'You decide',
    tags: ['custom', 'blank', 'freeform', 'build your own', 'operational'],
    intentPlaceholder: 'e.g., Describe anything — the AI will adapt to whatever goal you have in mind…',
    suggestions: [
      'Build a fully custom survey from scratch',
      'Combine multiple survey types into one instrument',
      'Create a unique research instrument for a novel use case',
    ],
  },
];

// Pre-computed lookups for O(1) access
export const SURVEY_TYPE_MAP = Object.fromEntries(SURVEY_TYPES.map((t) => [t.id, t]));

export const SURVEY_TYPES_BY_CATEGORY = SURVEY_TYPES.reduce((acc, type) => {
  if (!acc[type.category]) acc[type.category] = [];
  acc[type.category].push(type);
  return acc;
}, {});

export const CATEGORY_MAP = Object.fromEntries(SURVEY_CATEGORIES.map((c) => [c.id, c]));
