// Visual insight report generator — a self-contained, printable HTML report
// (browser "Save as PDF" works offline; native PDF/PPTX export is deploy-dependent
// and would add puppeteer/pptxgenjs). buildReportHtml is a pure function (testable).

function esc(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

/**
 * @param {object} data
 * @param {{title:string}} data.survey
 * @param {{nps?:number|null, csat?:number|null, responseCount?:number|null}} data.metrics
 * @param {Array<{name:string, sentiment?:string, volume?:number}>} data.topics
 * @param {string} [data.summary]
 * @returns {string} HTML document
 */
function buildReportHtml(data) {
  const { survey = {}, metrics = {}, topics = [], summary = '' } = data;
  const kpi = (label, val) =>
    `<div class="kpi"><div class="kpi-v">${val == null ? '—' : esc(val)}</div><div class="kpi-l">${esc(label)}</div></div>`;

  const topicRows = topics.length
    ? topics.map((t) =>
        `<tr><td>${esc(t.name)}</td><td>${esc(t.sentiment || '—')}</td><td>${t.volume ?? '—'}</td></tr>`).join('')
    : '<tr><td colspan="3" class="muted">No topics yet.</td></tr>';

  return `<!doctype html><html><head><meta charset="utf-8">
<title>${esc(survey.title || 'Insight Report')} — Experient</title>
<style>
  *{box-sizing:border-box} body{font-family:Inter,system-ui,sans-serif;color:#1a1a1a;margin:0;padding:40px;background:#fff}
  .brand{display:flex;align-items:center;gap:10px;margin-bottom:8px}
  .mark{width:28px;height:28px;border-radius:8px;background:linear-gradient(135deg,#2a4bd9,#8329c8);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700}
  h1{font-size:24px;margin:4px 0} .sub{color:#666;font-size:13px;margin-bottom:24px}
  .summary{background:#f5f7f9;border-left:3px solid #2a4bd9;padding:16px;border-radius:8px;margin-bottom:24px;line-height:1.6}
  .kpis{display:flex;gap:16px;margin-bottom:28px}
  .kpi{flex:1;background:#f5f7f9;border-radius:12px;padding:18px;text-align:center}
  .kpi-v{font-size:30px;font-weight:800;color:#2a4bd9} .kpi-l{font-size:12px;color:#666;text-transform:uppercase;letter-spacing:.04em;margin-top:4px}
  table{width:100%;border-collapse:collapse;font-size:14px} th,td{text-align:left;padding:10px;border-bottom:1px solid #eee}
  th{font-size:11px;text-transform:uppercase;color:#888;letter-spacing:.04em} .muted{color:#999;text-align:center}
  .foot{margin-top:32px;color:#aaa;font-size:11px}
  @media print{body{padding:24px}}
</style></head><body>
  <div class="brand"><span class="mark">◆</span><strong>Experient · Crystal Report</strong></div>
  <h1>${esc(survey.title || 'Insight Report')}</h1>
  <div class="sub">Generated ${esc(new Date().toISOString().slice(0, 10))}</div>
  ${summary ? `<div class="summary">${esc(summary)}</div>` : ''}
  <div class="kpis">
    ${kpi('NPS', metrics.nps)}
    ${kpi('CSAT', metrics.csat)}
    ${kpi('Responses', metrics.responseCount)}
  </div>
  <h2 style="font-size:16px">Top topics</h2>
  <table><thead><tr><th>Topic</th><th>Sentiment</th><th>Volume</th></tr></thead><tbody>${topicRows}</tbody></table>
  <div class="foot">Generated by Experient Crystal. Charts and narration are AI-assisted.</div>
</body></html>`;
}

module.exports = { buildReportHtml };
