interface AIDraftBadgeProps {
  reviewedAt: string | null
}

export function AIDraftBadge({ reviewedAt }: AIDraftBadgeProps) {
  const reviewDate = reviewedAt
    ? new Date(reviewedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long' })
    : null

  return (
    <div className="flex items-start gap-3 p-4 rounded-DEFAULT bg-surface-container-low ghost-border mb-8">
      <span
        className="material-symbols-outlined text-[20px] text-primary flex-shrink-0 mt-0.5"
        style={{ fontVariationSettings: "'FILL' 1" }}
      >
        auto_awesome
      </span>
      <div>
        <p className="font-label text-sm font-medium text-on-surface">
          AI-drafted
          {reviewDate ? `, human-reviewed ${reviewDate}` : ', pending human review'}
        </p>
        <p className="font-body text-xs text-on-surface-variant mt-0.5">
          This article was generated by Crystal AI and reviewed by the Experient documentation team.{' '}
          <a href="/legal/ai-content" className="text-primary hover:underline">
            Learn more
          </a>
        </p>
      </div>
    </div>
  )
}
