"""Deterministic metric computations. All functions return typed dicts."""
from __future__ import annotations
import math
import re
import statistics
from collections import Counter
from typing import Any

# Patterns that indicate a response has no real feedback content.
_NO_FEEDBACK_PATTERNS: frozenset[str] = frozenset({
    "n/a", "na", "none", "nothing", "no", "ok", "okay", "good",
    "fine", "alright", "yes", "idk", "pass", "-", "--",
})

# Synthetic score label prefixes generated by _score_to_text — these should
# never be fed back into topic clustering.
_SYNTHETIC_PREFIXES: tuple[str, ...] = (
    "promoter —",
    "detractor —",
    "passive —",
    "customer satisfaction:",
    "customer effort:",
    "extremely dissatisfied",
    "extremely satisfied",
    "rating:",
)


def is_meaningful_text(text: str, min_chars: int = 10, min_words: int = 3) -> bool:
    """Return True if text is worth ABSA and clustering.

    Filters out:
    - Text shorter than min_chars after stripping whitespace.
    - Fewer than min_words alphabetic tokens (length >= 2 after stripping punctuation).
    - Single/double-word "no feedback" patterns (n/a, ok, good, etc.).
    - Synthetic score labels produced by _score_to_text.

    Args:
        text: The candidate text string.
        min_chars: Minimum character count after strip (default 10).
                   Lowered from 15 so short but genuine phrases like
                   "It is great" (11 chars) are not rejected.
                   The min_words gate does the heavy lifting for noise.
        min_words: Minimum number of alphabetic word tokens (default 3).

    Returns:
        True if the text appears to contain genuine feedback.
    """
    stripped = text.strip()
    if len(stripped) < min_chars:
        return False

    # Check for synthetic score label prefixes (case-insensitive)
    lower = stripped.lower()
    for prefix in _SYNTHETIC_PREFIXES:
        if lower.startswith(prefix):
            return False

    # Count alphabetic tokens (len >= 2 after stripping punctuation)
    tokens = [
        re.sub(r"[^a-zA-Z]", "", tok)
        for tok in stripped.split()
    ]
    alpha_tokens = [t for t in tokens if len(t) >= 2]
    if len(alpha_tokens) < min_words:
        return False

    # Single/double-word "no feedback" patterns
    if len(alpha_tokens) <= 2:
        joined = " ".join(t.lower() for t in alpha_tokens)
        if joined in _NO_FEEDBACK_PATTERNS:
            return False

    return True

def compute_nps_ci(responses: list[dict], nps_field: str = "nps_score") -> dict:
    """Compute NPS with Wilson score CI. Returns {score, promoters, passives, detractors, n, ci_low, ci_high, below_minimum}."""
    scores = [r[nps_field] for r in responses if r.get(nps_field) is not None]
    n = len(scores)
    if n == 0:
        return {"score": None, "n": 0, "below_minimum": True}
    promoters   = sum(1 for s in scores if s >= 9) / n
    detractors  = sum(1 for s in scores if s <= 6) / n
    nps = round((promoters - detractors) * 100, 1)
    # Wilson score CI for NPS (treats promoter_rate and detractor_rate independently, difference)
    z = 1.96
    def wilson_ci(p, nn):
        if nn == 0: return (0.0, 0.0)
        center = (p + z**2 / (2 * nn)) / (1 + z**2 / nn)
        margin = z * math.sqrt((p * (1 - p) + z**2 / (4 * nn)) / (nn + z**2))
        return (max(0, center - margin), min(1, center + margin))
    p_lo, p_hi = wilson_ci(promoters, n)
    d_lo, d_hi = wilson_ci(detractors, n)
    ci_low  = round((p_lo - d_hi) * 100, 1)
    ci_high = round((p_hi - d_lo) * 100, 1)
    distribution = dict(Counter(int(s) for s in scores))
    return {
        "score": nps, "promoters": round(promoters * 100, 1),
        "passives": round((1 - promoters - detractors) * 100, 1),
        "detractors": round(detractors * 100, 1),
        "n": n, "ci_low": ci_low, "ci_high": ci_high,
        "distribution": distribution, "below_minimum": n < 30,
    }

def compute_csat(responses: list[dict], csat_field: str = "csat_score", scale: int = 5) -> dict:
    scores = [r[csat_field] for r in responses if r.get(csat_field) is not None]
    n = len(scores)
    if n == 0:
        return {"score": None, "n": 0, "below_minimum": True}
    mean = statistics.mean(scores)
    z = 1.96
    try:
        std = statistics.stdev(scores)
        margin = z * std / math.sqrt(n)
    except statistics.StatisticsError:
        margin = 0.0
    return {
        "score": round(mean, 2), "scale": scale,
        "ci_low": round(mean - margin, 2), "ci_high": round(mean + margin, 2),
        "n": n, "below_minimum": n < 30,
    }

def compute_ces(responses: list[dict], ces_field: str = "ces_score") -> dict:
    """Customer Effort Score (1-7 scale typically)."""
    scores = [r[ces_field] for r in responses if r.get(ces_field) is not None]
    n = len(scores)
    if n == 0:
        return {"score": None, "n": 0, "below_minimum": True}
    mean = statistics.mean(scores)
    return {"score": round(mean, 2), "n": n, "below_minimum": n < 30}

def compute_completion_rate(responses: list[dict]) -> dict:
    """Fraction of responses that have at least one non-empty answer."""
    n = len(responses)
    if n == 0:
        return {"rate": 0.0, "n": 0}
    def _has_answer(r: dict) -> bool:
        if r.get("completed") is True:
            return True
        answers = r.get("answers") or []
        return any(
            isinstance(a, dict) and a.get("value") not in (None, "", [])
            for a in answers
        )
    completed = sum(1 for r in responses if _has_answer(r))
    return {"rate": round(completed / n * 100, 1), "n": n}

def compute_response_trend(responses: list[dict], window_days: int = 30) -> list[dict]:
    """Group response counts by day for the last window_days days."""
    from datetime import datetime, timezone, timedelta
    cutoff = datetime.now(timezone.utc) - timedelta(days=window_days)
    by_day: Counter = Counter()
    for r in responses:
        ts = r.get("submitted_at") or r.get("created_at")
        if not ts:
            continue
        try:
            if isinstance(ts, str):
                dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
            else:
                dt = ts
            if dt >= cutoff:
                by_day[dt.strftime("%Y-%m-%d")] += 1
        except Exception:
            pass
    return [{"date": d, "count": c} for d, c in sorted(by_day.items())]

def _score_to_text(q_type: str, score: float, question_stem: str = "") -> str:
    """Convert a numeric survey score to a human-readable sentence for ABSA/clustering."""
    stem = question_stem.strip()

    if q_type == "nps":
        score_int = max(0, min(10, round(score)))
        if score_int >= 9:
            label = f"Promoter — very likely to recommend (NPS {score_int}/10)"
        elif score_int >= 7:
            label = f"Passive — somewhat likely to recommend (NPS {score_int}/10)"
        else:
            label = f"Detractor — unlikely to recommend (NPS {score_int}/10)"
        return f"{stem}: {label}" if stem else label

    if q_type == "csat":
        score_int = max(1, min(5, round(score)))
        labels = {1: "extremely dissatisfied", 2: "dissatisfied", 3: "neutral",
                  4: "satisfied", 5: "extremely satisfied"}
        label = f"{labels[score_int]} ({score_int}/5)"
        return f"{stem}: {label}" if stem else f"Customer satisfaction: {label}"

    if q_type == "ces":
        score_r = round(score, 1)
        if score_r <= 2.5:
            label = f"very easy experience (effort {score_r}/7)"
        elif score_r <= 4.5:
            label = f"moderate effort experience ({score_r}/7)"
        else:
            label = f"high effort, difficult experience ({score_r}/7)"
        return f"{stem}: {label}" if stem else f"Customer effort: {label}"

    # rating / slider — generic
    label = f"rated {round(score, 1)}"
    return f"{stem}: {label}" if stem else f"Rating: {round(score, 1)}"


def extract_open_texts(responses: list[dict], questions: list[dict]) -> list[dict]:
    """Extract answers for topic/sentiment analysis as {response_id, question_id, text}.

    Priority is determined by the survey's question types, not per-response:

      1. open_text / short_text  — actual customer words (best signal)
      2. multiple_choice / checkbox — structured selections (used only when the
         survey has NO open-text questions at all)
      3. csat / nps / ces / rating / slider — synthetic sentences from scores
         (last resort for score-only surveys)

    If the survey defines open_text questions, only open_text answers are
    returned — choice and score answers are never mixed in, even for respondents
    who skipped the open-text fields.  This prevents synthetic score labels like
    "Detractor — unlikely to recommend (NPS 3/10)" from polluting topic clusters.
    """
    open_types   = {"open_text", "short_text"}
    choice_types = {"multiple_choice", "checkbox"}
    score_types  = {"csat", "nps", "ces", "rating", "slider"}

    q_map        = {q["id"]: q for q in questions}
    open_qids    = {q["id"] for q in questions if q.get("type") in open_types}
    choice_qids  = {q["id"] for q in questions if q.get("type") in choice_types}
    score_qids   = {q["id"] for q in questions if q.get("type") in score_types}

    # ── Tier 1: open / short text ─────────────────────────────────────────────
    if open_qids:
        texts = []
        for r in responses:
            rid = str(r.get("id") or r.get("response_id") or "")
            for answer in (r.get("answers") or []):
                qid = answer.get("questionId", "")
                val = answer.get("value")
                if qid in open_qids and val and isinstance(val, str) and is_meaningful_text(val):
                    q_stem = q_map[qid].get("question", "")
                    texts.append({"response_id": rid, "question_id": qid,
                                  "text": val.strip(), "question": q_stem})
        return texts  # may be empty if all respondents skipped — caller handles that

    # ── Tier 2: multiple choice / checkbox ────────────────────────────────────
    if choice_qids:
        texts = []
        for r in responses:
            rid = str(r.get("id") or r.get("response_id") or "")
            for answer in (r.get("answers") or []):
                qid = answer.get("questionId", "")
                val = answer.get("value")
                if qid not in choice_qids:
                    continue
                q_stem = q_map[qid].get("question", "")
                if isinstance(val, str) and val.strip():
                    text = f"{q_stem} → {val.strip()}" if q_stem else val.strip()
                    texts.append({"response_id": rid, "question_id": qid, "text": text})
                elif isinstance(val, list):
                    for opt in val:
                        if isinstance(opt, str) and opt.strip():
                            text = f"{q_stem} → {opt.strip()}" if q_stem else opt.strip()
                            texts.append({"response_id": rid, "question_id": qid, "text": text})
        return texts

    # ── Tier 3: score-only surveys (NPS / CSAT / CES / rating / slider) ───────
    texts = []
    for r in responses:
        rid = str(r.get("id") or r.get("response_id") or "")
        for answer in (r.get("answers") or []):
            qid = answer.get("questionId", "")
            val = answer.get("value")
            if qid not in score_qids or val is None:
                continue
            try:
                score = float(val)
            except (TypeError, ValueError):
                continue
            q_def  = q_map.get(qid, {})
            q_type = q_def.get("type", "rating")
            q_stem = q_def.get("question", "")
            text = _score_to_text(q_type, score, q_stem)
            if text:
                texts.append({"response_id": rid, "question_id": qid, "text": text})
    return texts


def compute_effort_score(texts: list[str]) -> float:
    """Linguistic effort score 1-7 (higher = more customer effort/frustration).

    Scores are derived from four independent signals:
    - Length: longer responses signal more effort to articulate a problem.
    - Frustration keywords: explicit negative/effort vocabulary.
    - Punctuation intensity: multiple ! or ? signals emotional escalation.
    - Negation density: 'not', 'never', 'can't', etc. signal unmet expectations.
    """
    FRUSTRATION = {
        'hard', 'difficult', 'frustrating', 'annoying', 'complicated',
        'confusing', 'terrible', "couldn't", "can't", 'impossible',
        'forever', 'broken', 'useless', 'awful', 'worst',
    }
    NEGATION = {'not', "n't", 'no', 'never', 'without', 'lack', "didn't", "doesn't"}

    if not texts:
        return 4.0

    scores = []
    for text in texts:
        lower = text.lower()
        words = lower.split()
        word_count = len(words)

        # Length signals effort (normalised: 0–1.5 points)
        length_factor = min(1.5, word_count / 25.0)
        # Frustration keywords (0–2 points)
        frustration_factor = min(2.0, sum(1 for w in FRUSTRATION if w in lower) * 0.5)
        # Punctuation intensity (0–1 point)
        punct_factor = min(1.0, (text.count('!') + text.count('?')) * 0.3)
        # Negation density (0–1 point)
        neg_factor = min(1.0, sum(1 for w in NEGATION if w in words) * 0.25)

        raw = 1.5 + length_factor + frustration_factor + punct_factor + neg_factor
        scores.append(min(7.0, max(1.0, raw)))

    return round(sum(scores) / len(scores), 2)


def compute_response_trend_analysis(responses: list[dict], window_days: int = 30) -> dict:
    """Extended trend: daily counts + linear trend + anomaly flag + 7-day forecast."""
    daily = compute_response_trend(responses, window_days)

    counts = [d['count'] for d in daily]
    if len(counts) < 3:
        return {
            'daily': daily,
            'trend': 'stable',
            'slope': 0.0,
            'delta_pct': 0,
            'anomaly': False,
            'forecast_7d': None,
            'recent_avg': 0.0,
        }

    # Simple linear regression (OLS, no libraries)
    n = len(counts)
    x = list(range(n))
    x_mean = sum(x) / n
    y_mean = sum(counts) / n

    numerator = sum((x[i] - x_mean) * (counts[i] - y_mean) for i in range(n))
    denominator = sum((xi - x_mean) ** 2 for xi in x)
    slope = numerator / denominator if denominator != 0 else 0.0

    # Trend direction based on recent vs earlier average
    recent_avg = sum(counts[-7:]) / max(1, len(counts[-7:]))
    earlier_avg = sum(counts[:-7]) / max(1, len(counts[:-7]))
    delta_pct = round(((recent_avg - earlier_avg) / max(1, earlier_avg)) * 100, 1)
    trend = 'up' if delta_pct > 15 else 'down' if delta_pct < -15 else 'stable'

    # Anomaly: last 3 days avg > 2× overall avg
    last3_avg = sum(counts[-3:]) / max(1, len(counts[-3:]))
    anomaly = last3_avg > (y_mean * 2.0) and y_mean > 0

    # Forecast next 7 days (linear extrapolation, capped at 0)
    forecast_7d = max(0, round(counts[-1] + slope * 7))

    return {
        'daily': daily,
        'trend': trend,
        'slope': round(slope, 3),
        'delta_pct': delta_pct,
        'anomaly': anomaly,
        'forecast_7d': forecast_7d,
        'recent_avg': round(recent_avg, 1),
    }


def filter_responses_by_window(responses: list[dict], window: str) -> list[dict]:
    """Filter responses to a time window.

    Args:
        responses: List of response dicts (must have 'submitted_at' or 'created_at').
        window: One of 'all_time', 'last_7d', 'last_30d'.

    Returns:
        Filtered response list. Responses without a timestamp are always included
        (to avoid silently discarding data).
    """
    from datetime import datetime, timezone, timedelta

    if window == 'all_time':
        return responses

    days = {'last_7d': 7, 'last_30d': 30}.get(window, 999)
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)

    result = []
    for r in responses:
        ts = r.get('submitted_at') or r.get('created_at')
        if not ts:
            result.append(r)
            continue
        if isinstance(ts, str):
            try:
                ts = datetime.fromisoformat(ts.replace('Z', '+00:00'))
            except Exception:
                result.append(r)
                continue
        if ts.tzinfo is None:
            ts = ts.replace(tzinfo=timezone.utc)
        if ts >= cutoff:
            result.append(r)
    return result
