-- Action Recommendations: post-pipeline recommended next steps
-- Generated by the action-recommender XOS skill after every successful insight publish.
-- Upserted per survey+org (latest wins) since recommendations evolve with new data.

CREATE TABLE IF NOT EXISTS action_recommendations (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    survey_id     UUID NOT NULL,
    org_id        UUID NOT NULL,
    actions_json  JSONB NOT NULL DEFAULT '[]',  -- list of ActionProposal objects
    urgency_level TEXT NOT NULL DEFAULT 'this_month'
                      CHECK (urgency_level IN ('immediate', 'this_week', 'this_month', 'strategic')),
    summary       TEXT NOT NULL DEFAULT '',
    generated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    dismissed_ids TEXT[] DEFAULT '{}'          -- action IDs the user has dismissed
);

-- One recommendation set per survey per org (UPSERT target)
CREATE UNIQUE INDEX IF NOT EXISTS idx_action_recommendations_survey_org
    ON action_recommendations (survey_id, org_id);

CREATE INDEX IF NOT EXISTS idx_action_recommendations_org
    ON action_recommendations (org_id, generated_at DESC);

COMMENT ON TABLE action_recommendations IS
    'Recommended next actions after insight generation. '
    'Generated by action-recommender XOS skill, upserted per survey per pipeline run.';
